# Generated by Django 4.0.2 on 2022-07-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoscowCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
                ('city_url', models.CharField(max_length=255)),
                ('city_population', models.IntegerField()),
            ],
        ),
    ]
